url: "https://yoogottamk.github.io"
baseurl: ""
title: "yoogottamk"
email: "yoogottamk@outlook.com"
github_username: "yoogottamk"
timezone: "Asia/Kolkata"
exclude: ["package*.json", "gulpfile.js", "README.md", "screens"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Yoogottam Khandelwal"
      comments: true
      permalink: /blog/:title
  -
    scope:
      path: "css"
    values:
      layout: "null"
      navbarHeight: "60px"
      darkBg: "#181a1b"
      darkFg: "#a6a4a2"
      lightBg: "#ffffff"
      lightFg: "#000000"
  -
    scope:
      path: "js"
    values:
      layout: "null"
      navbarHeight: 60

collections:
  projects:
    output: true
    layout: "project"
    permalink: /projects/:title
  snippets:
    output: true
    layout: "snippet"
    permalink: /snippets/:title
